### ISSUE TITLE
sc-list styling

### ISSUE THREAD

**Issue by angvishvish** [changer/sc-client-components#3]
Instead of having icons of the left side of the list, we can pull it on the right, which will remove the extra 20px white space for each list.

![screen shot 2015-01-21 at 3 03 11 pm](https://cloud.githubusercontent.com/assets/3169957/5834003/13da5146-a17f-11e4-8a16-4bd920fb0ee8.png)
![screen shot 2015-01-21 at 3 03 45 pm](https://cloud.githubusercontent.com/assets/3169957/5834004/13e11422-a17f-11e4-945f-2d983cbfee6a.png)
![screen shot 2015-01-21 at 3 05 32 pm](https://cloud.githubusercontent.com/assets/3169957/5834005/13e16206-a17f-11e4-932c-32a79bba7ba4.png)

**Comment by madhums** [comment]
if you have a long list, it makes it hard to read.
